\set ON_ERROR_STOP on

CREATE SCHEMA movie_rentals;
SET search_path = movie_rentals;

CREATE TABLE cast_roles (
  id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  movie int8 NOT NULL,
  person int8 NOT NULL,
  character_name text
);
CREATE TABLE crew_roles (
  id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  movie int8 NOT NULL,
  person int8 NOT NULL,
  department text,
  job text
);
CREATE TABLE customers (
  id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  full_name text NOT NULL,
  email text,
  phone text
);
CREATE TABLE genres (
  id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text UNIQUE NOT NULL
);
CREATE TABLE items (
  id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  barcode uuid UNIQUE DEFAULT gen_random_uuid() NOT NULL,
  movie int8 NOT NULL,
  store int8 NOT NULL
);
CREATE TABLE movies (
  id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title text NOT NULL,
  overview text,
  release_date date,
  lang text,
  rating text,
  popularity float4,
  vote_count int4,
  vote_average float4,
  budget int8,
  revenue int8,
  runtime int4
);
CREATE TABLE movies_genres (
  id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  movie int4 NOT NULL,
  genre int4 NOT NULL,
  UNIQUE (movie, genre)
);
CREATE TABLE movies_studios (
  id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  movie int8 NOT NULL,
  studio int8 NOT NULL,
  UNIQUE (movie, studio)
);
CREATE TABLE people (
  id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL,
  also_known_as _text NOT NULL DEFAULT '{}',
  birth_date date,
  death_date date,
  popularity float4,
  imdb_id text,
  biography text
);
CREATE TABLE rentals (
  id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  customer int8 NOT NULL,
  item int8 NOT NULL,
  time_out timestamptz NOT NULL,
  time_in timestamptz
);
CREATE TABLE stores (
  id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  street_name text,
  phone text
);
CREATE TABLE studios (
  id int8 PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL
);


INSERT INTO cast_roles (movie, person, character_name)
SELECT film_id, person_id, film_character FROM bluebox.film_cast;

INSERT INTO crew_roles (movie, person, department, job)
SELECT film_id, person_id, department, job FROM bluebox.film_crew;

INSERT INTO customers (id, full_name, email, phone)
SELECT customer_id, full_name, email, phone FROM bluebox.customer;

INSERT INTO genres (id, name)
SELECT genre_id, name FROM bluebox.film_genre;

INSERT INTO items (id, movie, store)
SELECT inventory_id, film_id, store_id FROM bluebox.inventory;

insert into movies (
  id,
  title,
  overview,
  release_date,
  lang,
  rating,
  popularity,
  vote_count,
  vote_average,
  budget,
  revenue,
  runtime
)
SELECT
  film_id,
  title,
  overview,
  release_date,
  original_language,
  rating,
  popularity,
  vote_count,
  vote_average,
  budget,
  revenue,
  runtime
FROM bluebox.film;
UPDATE movies SET budget = NULL WHERE budget = 0;
UPDATE movies SET revenue = NULL WHERE revenue = 0;
UPDATE movies SET runtime = NULL WHERE runtime = 0;

INSERT INTO movies_genres (movie, genre)
SELECT film_id, unnest(genre_ids) FROM bluebox.film;

INSERT INTO movies_studios (movie, studio)
SELECT film_id, production_company_id FROM bluebox.film_production_company;

INSERT INTO people (
  id,
  name,
  also_known_as,
  birth_date,
  death_date,
  popularity,
  imdb_id,
  biography
)
SELECT
  person_id,
  name,
  also_known_as,
  birth_date,
  death_date,
  popularity,
  imdb_id,
  biography
FROM bluebox.person;

INSERT INTO rentals (id, customer, item, time_out, time_in)
SELECT
  rental_id,
  customer_id,
  inventory_id,
  lower(rental_period),
  upper(rental_period)
FROM bluebox.rental;

INSERT INTO stores (id, street_name, phone)
SELECT
  store_id,
  street_name,
  phone
FROM bluebox.store;
-- Get rid of empty strings in stores table
UPDATE stores SET street_name = 'Centre St' WHERE id = 3;
UPDATE stores SET street_name = 'Perkins St' WHERE id = 6;
UPDATE stores SET street_name = 'Amory St' WHERE id = 10;
UPDATE stores SET street_name = 'Lamartine St' WHERE id = 12;
UPDATE stores SET street_name = 'South St' WHERE id = 17;
UPDATE stores SET street_name = 'Pond St' WHERE id = 42;
UPDATE stores SET street_name = 'Washington St' WHERE id = 57;
UPDATE stores SET street_name = 'Saint Rose St' WHERE id = 60;
UPDATE stores SET street_name = 'Forest Hills St' WHERE id = 77;
UPDATE stores SET street_name = 'Arborway' WHERE id = 81;
UPDATE stores SET street_name = 'Seaverns Ave' WHERE id = 89;
UPDATE stores SET street_name = 'Chestnut Ave' WHERE id = 92;
UPDATE stores SET street_name = 'Boylston Ave' WHERE id = 97;
UPDATE stores SET street_name = 'Beaufort Rd' WHERE id = 119;
UPDATE stores SET street_name = 'Green St' WHERE id = 134;
UPDATE stores SET street_name = 'Spring Park Ave' WHERE id = 190;
UPDATE stores SET street_name = 'Greenough Ave' WHERE id = 191;

INSERT INTO studios (id, name)
SELECT production_company_id, production_company_name
FROM bluebox.production_company;

-- Make Galaxy Quest have id 1! 😎
UPDATE movies SET id = 1 WHERE title = 'Galaxy Quest'; -- Was 926
UPDATE cast_roles SET movie = 1 WHERE movie = 926;
UPDATE crew_roles SET movie = 1 WHERE movie = 926;
UPDATE movies_studios SET movie = 1 WHERE movie = 926;
UPDATE movies_genres SET movie = 1 WHERE movie = 926;

-- Galaxy Quest has no items (and thus no rentals)! ☹️
--
-- Steal the items (and related rentals) from the movie "Fast X" (id 385687)
-- which happens to have the most rentals. Re-assign this to Galaxy Quest
-- instead! 😎
UPDATE items SET movie = 1 WHERE movie = 385687;

-- Update sequences
SELECT setval(pg_get_serial_sequence('cast_roles', 'id'), MAX(id) + 1, false) FROM cast_roles;
SELECT setval(pg_get_serial_sequence('crew_roles', 'id'), MAX(id) + 1, false) FROM crew_roles;
SELECT setval(pg_get_serial_sequence('customers', 'id'), MAX(id) + 1, false) FROM customers;
SELECT setval(pg_get_serial_sequence('genres', 'id'), MAX(id) + 1, false) FROM genres;
SELECT setval(pg_get_serial_sequence('items', 'id'), MAX(id) + 1, false) FROM items;
SELECT setval(pg_get_serial_sequence('movies', 'id'), MAX(id) + 1, false) FROM movies;
SELECT setval(pg_get_serial_sequence('movies_genres', 'id'), MAX(id) + 1, false) FROM movies_genres;
SELECT setval(pg_get_serial_sequence('movies_studios', 'id'), MAX(id) + 1, false) FROM movies_studios;
SELECT setval(pg_get_serial_sequence('people', 'id'), MAX(id) + 1, false) FROM people;
SELECT setval(pg_get_serial_sequence('rentals', 'id'), MAX(id) + 1, false) FROM rentals;
SELECT setval(pg_get_serial_sequence('stores', 'id'), MAX(id) + 1, false) FROM stores;
SELECT setval(pg_get_serial_sequence('studios', 'id'), MAX(id) + 1, false) FROM studios;


ALTER TABLE cast_roles ADD CONSTRAINT cast_roles_movie_fkey
FOREIGN KEY (movie) REFERENCES movies (id);

ALTER TABLE cast_roles ADD CONSTRAINT cast_roles_person_fkey
FOREIGN KEY (person) REFERENCES people (id);

ALTER TABLE crew_roles ADD CONSTRAINT crew_roles_movie_fkey
FOREIGN KEY (movie) REFERENCES movies (id);

ALTER TABLE crew_roles ADD CONSTRAINT crew_roles_person_fkey
FOREIGN KEY (person) REFERENCES people (id);

ALTER TABLE items ADD CONSTRAINT items_movie_fkey
FOREIGN KEY (movie) REFERENCES movies (id);

ALTER TABLE items ADD CONSTRAINT items_store_fkey
FOREIGN KEY (store) REFERENCES stores (id);

ALTER TABLE movies_genres ADD CONSTRAINT movies_genres_movie_fkey
FOREIGN KEY (movie) REFERENCES movies (id);

ALTER TABLE movies_genres ADD CONSTRAINT movies_genres_genre_fkey
FOREIGN KEY (genre) REFERENCES genres (id);

ALTER TABLE movies_studios ADD CONSTRAINT movies_studios_movie_fkey
FOREIGN KEY (movie) REFERENCES movies (id);

ALTER TABLE movies_studios ADD CONSTRAINT movies_studios_studio_fkey
FOREIGN KEY (studio) REFERENCES studios (id);

ALTER TABLE rentals ADD CONSTRAINT rentals_customer_fkey
FOREIGN KEY (customer) REFERENCES customers (id);

ALTER TABLE rentals ADD CONSTRAINT rentals_item_fkey
FOREIGN KEY (item) REFERENCES items (id);

