name: Update project on PR edit
on:
  pull_request_target:
    types: [assigned, unassigned, labeled, unlabeled, opened, edited, closed, reopened, synchronize, converted_to_draft, ready_for_review, locked, unlocked, review_requested, review_request_removed, auto_merge_enabled, auto_merge_disabled]

jobs:
  update_project_on_pr_edit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          cd .github/actions/project_update/
          pip install -r requirements.txt

      - name: Update timestamp
        run: |
          cd .github/actions/project_update/
          python project_update.py ${{ github.event.pull_request.node_id }} --timestamp ${{ github.event.pull_request.updated_at }}
        env:
          MATHESAR_ORG_GITHUB_TOKEN: ${{secrets.MATHESAR_ORG_GITHUB_TOKEN}}
