name: Update project on issue assignment
on:
  issues:
    types: [assigned, unassigned]

jobs:
  update_project_on_issue_assign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          cd .github/actions/project_update/
          pip install -r requirements.txt

      - name: Update priority for assigned issues
        if: ${{ github.event.issue.assignees[0] != null }}
        run: |
          cd .github/actions/project_update/
          python project_update.py ${{ github.event.issue.node_id }} --priority Active
        env:
          MATHESAR_ORG_GITHUB_TOKEN: ${{secrets.MATHESAR_ORG_GITHUB_TOKEN}}

      - name: Update priority for non-assigned issues
        if: ${{ github.event.issue.assignees[0] == null }}
        run: |
          cd .github/actions/project_update/
          python project_update.py ${{ github.event.issue.node_id }} --priority Backlog
        env:
          MATHESAR_ORG_GITHUB_TOKEN: ${{secrets.MATHESAR_ORG_GITHUB_TOKEN}}
